version: "3.9"

services:

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - BACKEND_URL=http://backend:5001
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - db_data:/app/data
    expose:
      - "5001"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  db_data: